---
title: "Chick Weight Example"
author: "Vidushi Kataria"
date: "`r Sys.Date()`"
output: ioslides_presentation

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(ggdist)
```

## What is this?

This is our three slide presentation about Chick Weight!

## Research Question

How does diet impact chick growth?

## Little Research Question

Also sometimes called a "fork"
>- Descriptive: On day 21, chicks in which diet group had the highest weight?
>- As a research question: After 21 days, do the different diets lead to different weight?

## Results

```{r warning = FALSE}
ChickWeight %>%
  filter(Time == 21) %>%
  ggplot(aes(y = weight, x = Diet)) +
  stat_summary(geom = "bar",
               fun = mean) +
  stat_summary(geom = "errorbar",
               fun.data = mean_se,
               width = 0.2)
```

## Results 2.0
```{r}
ChickWeight %>%
  filter(Time == 21) %>%
  ggplot(aes(y = weight, x = Diet)) +
  stat_halfeye() +
  labs(y = "Weight in Grams on Day 21") +
  theme_minimal()
```

## Slide 2

## Slide 3



