---
title: "Data Exercise 2: Mice Jumping (Parker)"
author: Vidushi Kataria
date: "`r Sys.Date()`" 
output: html_notebook
---

# Libraries

```{r}
library(tidyverse)
```


```{r}
files <- list.files(path = "jumping_data_parker/",
                         pattern = "*.csv",
                         full.names = TRUE)

files
```


```{r}
convert_columns <- function(file) {
  file <- file %>%
    mutate(sex = case_when(sex == FALSE ~ "F",
                         sex == "M" ~ "M"),
           date = as.character(date))
}
```


```{r}
raw_data <- map(files, read_csv) %>%
  map(convert_columns) %>%
  bind_rows()
```


# inspect data
```{r}
raw_data %>%
  distinct(sex)
```
```{r}
raw_data %>%
  distinct(condition)
```
```{r}
raw_data %>%
  distinct(laser_trial)
```

# explore the data
```{r}
summary_data <- raw_data %>%
  group_by(subject, distance) %>%
  summarise(succ_rate = sum(outcome == 1)/n())
```


```{r}
summary_data %>%
  ggplot(aes(x = succ_rate)) +
  geom_histogram()
```

# plot the data

```{r}
summary_data %>%
  ggplot(aes(x = distance,
             y = succ_rate,
             group = subject)) +
  geom_line() +
  ylim(0, 1)
```

```{r}
raw_data %>%
  group_by(subject, distance) %>%
  mutate(succ_rate_NOabort = sum(outcome == 1)/(n() - sum(outcome == 2)))
```

```{r}
raw_data %>%
  group_by(subject, distance) %>%
# filter(outcome == 1 | outcome == 0)
# filter(outcome != 2) 
  filter(outcome %in% c(0, 1)) %>%
  summarise(succ_rate = sum(outcome == 1)/n()) %>%
  ggplot(aes(x = distance,
             y = succ_rate,
             group = subject)) +
  geom_line() +
  ylim(0, 1)
```
# Day 2

3 goals today
- Make our plot look (literally) like theirs in terms of the visual features
- Explore a different feature of the dataset. What other questions might we ask, what plots will allow us to answer them?
- 

```{r}
raw_data %>%
  group_by(subject, distance) %>%
# filter(outcome == 1 | outcome == 0)
# filter(outcome != 2) 
  filter(outcome %in% c(0, 1)) %>%
  summarise(succ_rate = sum(outcome == 1)/n()) %>%
  ggplot(aes(x = distance,
             y = succ_rate)) +
  geom_line(aes(group = subject), alpha = 0.3, color = "darkblue") +
  stat_summary(fun.data = "mean_se", geom = "errorbar", width = 0.2, color = "darkblue") +
  stat_summary(fun.y = mean, geom = "line", color = "darkblue") + 
  ylim(0, 1) +
  xlim(10, 25) +
  labs(x = "gap distance (cm)",
       y = "success rate") +
  theme(panel.background = element_rect(fill = "white"),
        axis.line = element_line(color = "black", linewidth = 0.5)) +
  annotate(geom = "text", label = "binocular",
           x = 11, y = 0.1, color = "darkblue")
  
```

## explore something new

```{r}
raw_data %>%
  distinct(experimenter)
```

```{r}
raw_data %>%
  filter(outcome %in% c(0,1)) %>%
  group_by(subject, experimenter) %>%
  summarise(succ_rate = sum(outcome == 1)/n()) %>%
  ggplot(aes(y = succ_rate,
             x = experimenter)) +
  geom_jitter(alpha = 0.3, width = 0.1, height = 0) +
  ylim(0, 1)
```


